--- MAKEFILE_ORIG
+++ MAKEFILE_WINDOWS
@@ -226,7 +226,7 @@
 endif
 
 $(LIBPD): ${PD_FILES:.c=.o} ${UTIL_FILES:.c=.o} ${EXTRA_FILES:.c=.o}
-	$(CC) -o $(LIBPD) $^ $(LDFLAGS) -lm -lpthread
+	$(CC) -o $(LIBPD) $^ $(LDFLAGS) -Wl,-Bstatic -lm -Wl,-Bstatic -lpthread
 
 $(LIBPD_STATIC): ${PD_FILES:.c=.o} ${UTIL_FILES:.c=.o} ${EXTRA_FILES:.c=.o}
 	ar rcs $(LIBPD_STATIC) $^
